name: Propuesta
description: Una mejora o una capacidad nueva
title: "[propuesta] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problema
    attributes:
      label: Qué problema resuelve
    validations:
      required: true
  - type: textarea
    id: propuesta
    attributes:
      label: Qué proponés
    validations:
      required: true
  - type: textarea
    id: alternativas
    attributes:
      label: Alternativas que consideraste
    validations:
      required: false
